const KEY='kucharzyna-data-v2';
const seed=[
{name:'Pizza Napoletana',category:'Pizza',yield:'10 kulek',ingredients:[['Mąka 00',1000,'g'],['Woda',650,'g'],['Sól',30,'g'],['Drożdże świeże',1,'g']],steps:['Wymieszaj mąkę z większością wody.','Dodaj sól, następnie resztę wody i drożdże.','Wyrób do uzyskania gładkiego, elastycznego ciasta.','Fermentuj, podziel na kulki i prowadź do wypieku.'],notes:'Dopasuj drożdże do temperatury i czasu fermentacji.',source:''},
{name:'Carbonara',category:'Pasta',yield:'10 porcji',ingredients:[['Makaron świeży',1500,'g'],['Guanciale',500,'g'],['Żółtko',20,'szt'],['Pecorino Romano',400,'g'],['Pieprz czarny',25,'g']],steps:['Podsmaż guanciale i zachowaj tłuszcz.','Utrzyj żółtka z pecorino i pieprzem.','Ugotuj makaron al dente i zachowaj wodę.','Połącz poza ogniem, budując emulsję wodą z makaronu.'],notes:'Przy dużej produkcji bazę sera i żółtek trzymaj osobno.',source:''},
{name:'Sos pomidorowy z cebulą',category:'Sosy',yield:'ok. 3 l',ingredients:[['Pomidory San Marzano',10,'kg'],['Cebula',800,'g'],['Oliwa',120,'ml'],['Sól',70,'g'],['Bazylia',40,'g']],steps:['Zeszklij cebulę na oliwie.','Dodaj pomidory i gotuj do koncentracji.','Rozgnieć większe kawałki.','Wystudź, zmiksuj i dopraw.'],notes:'Nie przesalaj bazy, jeśli będzie redukowana.',source:''},
{name:'Pizza in Teglia',category:'Pizza',yield:'1 blacha 30×40',ingredients:[['Mąka 00',1000,'g'],['Woda',780,'g'],['Sól',25,'g'],['Drożdże świeże',3,'g'],['Oliwa',30,'g']],steps:['Wprowadź wodę stopniowo do mąki.','Dodaj sól, drożdże i na końcu oliwę.','Fermentuj w masie, przełóż na naoliwioną blachę.','Rozciągnij delikatnie i wypiekaj do chrupkości.'],notes:'Pracuj mokrymi lub natłuszczonymi dłońmi.',source:''},
{name:'Limoncello',category:'Napoje',yield:'ok. 2 l',ingredients:[['Alkohol 95%',1000,'ml'],['Skórka z cytryn',12,'szt'],['Woda',700,'ml'],['Cukier',500,'g']],steps:['Zdejmij cienko żółtą część skórek.','Maceruj skórki w alkoholu.','Przygotuj i ostudź syrop.','Połącz, przefiltruj i odstaw.'],notes:'Nie ścinaj białej części skórki.',source:''}
].map((r,i)=>({...r,id:'seed-'+i,tags:[]}));
let state=load();let currentTab='home',selected=null,filter='Wszystko',query='';
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.recipes)return x}catch(e){}return{recipes:seed,shopping:[],favorites:[],sources:[],settings:{dark:null}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function render(){document.body.classList.toggle('dark',state.settings.dark===true||(state.settings.dark===null&&matchMedia('(prefers-color-scheme: dark)').matches));document.querySelectorAll('#tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab));const s=document.getElementById('screen');s.innerHTML=selected?recipeDetail(selected):`<div class="content">${({home,recipes,cook,shopping,more,web}[currentTab]||home)()}</div>`}
function home(){const fav=state.recipes.filter(r=>state.favorites.includes(r.id));return `<div class="hero"><div class="eyebrow">Kucharzyna v2</div><h1>Co dziś gotujemy?</h1><p>Twoja prywatna baza receptur + narzędzia do pracy na kuchni.</p></div><div class="grid"><div class="card stat"><div class="num">${state.recipes.length}</div><div class="label">receptur</div></div><div class="card stat"><div class="num">${new Set(state.recipes.map(r=>r.category)).size}</div><div class="label">kategorii</div></div><div class="card stat"><div class="num">${state.shopping.length}</div><div class="label">zakupów</div></div><div class="card stat"><div class="num">${fav.length}</div><div class="label">ulubionych</div></div></div><div class="section-head"><h2>Szybkie akcje</h2></div><div class="action-grid"><button class="action" onclick="openAdd()"><span>＋</span>Nowa receptura</button><button class="action" onclick="openImportText()"><span>↥</span>Dodaj z tekstu</button><button class="action" onclick="currentTab='web';render()"><span>⌕</span>Szukaj w sieci</button><button class="action" onclick="currentTab='shopping';render()"><span>✓</span>Zakupy</button></div><div class="section-head"><h2>Ostatnie</h2><button class="link-btn" onclick="currentTab='recipes';render()">Wszystkie</button></div>${recipeRows(state.recipes.slice(0,5))}`}
function recipes(){let cats=['Wszystko',...new Set(state.recipes.map(r=>r.category))];let list=state.recipes.filter(r=>(filter==='Wszystko'||r.category===filter)&&((r.name+' '+r.category+' '+r.tags.join(' ')).toLowerCase().includes(query.toLowerCase())));return `<div class="hero"><div class="eyebrow">Biblioteka</div><h1>Receptury</h1><p>Wszystkie Twoje receptury w jednym miejscu.</p></div><div class="search">⌕<input value="${esc(query)}" placeholder="Szukaj receptury..." oninput="query=this.value;filterRecipes()"></div><div class="chips">${cats.map(c=>`<button class="chip ${filter===c?'active':''}" onclick="filter='${esc(c)}';render()">${esc(c)}</button>`).join('')}</div><div id="recipeResults" class="recipe-list" style="margin-top:12px">${recipeRows(list)}</div><button class="fab" onclick="openAdd()">＋</button>`}
function filterRecipes(){document.getElementById('recipeResults').innerHTML=recipeRows(state.recipes.filter(r=>(filter==='Wszystko'||r.category===filter)&&((r.name+' '+r.category+' '+r.tags.join(' ')).toLowerCase().includes(query.toLowerCase()))))}
function recipeRows(list){if(!list.length)return `<div class="empty"><strong>Nic tu nie ma</strong>Dodaj recepturę albo zaimportuj ją z tekstu.</div>`;return `<div class="recipe-list">${list.map(r=>`<button class="recipe-row" onclick="openRecipe('${r.id}')"><div style="text-align:left"><div class="title">${esc(r.name)} ${state.favorites.includes(r.id)?'★':''}</div><div class="meta">${esc(r.yield||'')} · ${esc(r.category)}</div><span class="badge">${r.ingredients.length} składników</span></div><div class="chev">›</div></button>`).join('')}</div>`}
function recipeDetail(r){return `<div class="content"><div class="detail-head"><button class="back" onclick="selected=null;render()">‹</button><div class="detail-title"><h1>${esc(r.name)}</h1><p>${esc(r.category)} · ${esc(r.yield||'')}</p></div><button class="star" onclick="toggleFav('${r.id}')">${state.favorites.includes(r.id)?'★':'☆'}</button></div><div class="two"><button class="secondary" onclick="openScale('${r.id}')">⚖️ Przelicz</button><button class="secondary" onclick="openEdit('${r.id}')">✎ Edytuj</button></div>${r.source?`<div class="source-box">Źródło: <a href="${esc(r.source)}" target="_blank" rel="noopener">${esc(r.source)}</a></div>`:''}<div class="panel"><h3>Składniki</h3>${r.ingredients.map(i=>`<div class="ingredient"><div>${esc(i[0])}</div><div class="amount">${i[1]}</div><div class="unit">${esc(i[2])}</div></div>`).join('')}</div><div class="panel"><h3>Technologia</h3>${r.steps.map((x,i)=>`<div class="step"><div class="stepno">${i+1}</div><div>${esc(x)}</div></div>`).join('')}</div>${r.notes?`<div class="panel"><h3>Własne uwagi</h3><div class="note-box">${esc(r.notes).replace(/\n/g,'<br>')}</div></div>`:''}<div class="two"><button class="secondary" onclick="addIngredientsToShopping('${r.id}')">＋ Do zakupów</button><button class="secondary danger" onclick="deleteRecipe('${r.id}')">Usuń</button></div></div>`}
function cook(){return `<div class="hero"><div class="eyebrow">Tryb pracy</div><h1>Gotuję</h1><p>Wybierz recepturę, przelicz ilość i pracuj krok po kroku.</p></div>${recipeRows(state.recipes)}`}
function shopping(){return `<div class="hero"><div class="eyebrow">Produkcja</div><h1>Zakupy</h1><p>${state.shopping.length?'Lista rzeczy do ogarnięcia.':'Lista jest pusta.'}</p></div>${state.shopping.length?`<div class="recipe-list">${state.shopping.map((x,i)=>`<label class="recipe-row"><span style="display:flex;gap:10px;align-items:center"><input type="checkbox" onchange="toggleShop(${i})" ${x.done?'checked':''} style="width:20px;height:20px"><span class="${x.done?'done':''}">${esc(x.name)}</span></span><b>${x.amount?esc(String(x.amount)+' '+(x.unit||'')):''}</b></label>`).join('')}</div><button class="secondary" style="width:100%;margin-top:10px" onclick="clearDone()">Wyczyść odhaczone</button>`:`<div class="empty"><strong>Zero pozycji</strong>Dodawaj składniki z receptur.</div>`}`}
function web(){return `<div class="hero"><div class="eyebrow">Internet</div><h1>Szukaj przepisów</h1><p>Kucharzyna nie kopiuje całego internetu. Możesz wyszukać przepis, otworzyć źródło i zapisać własną wersję w swojej bazie.</p></div><div class="search"><input id="webq" placeholder="np. pizza napoletana, carbonara..." onkeydown="if(event.key==='Enter')webSearch()"><button class="primary small" onclick="webSearch()">Szukaj</button></div><div class="panel"><h3>Szybkie wyszukiwanie</h3><div class="action-grid"><button class="action" onclick="webSearch('site:kwestiasmaku.com')">Kwestia Smaku</button><button class="action" onclick="webSearch('site:aniagotuje.pl')">AniaGotuje</button><button class="action" onclick="webSearch('site:jadlonomia.com')">Jadłonomia</button><button class="action" onclick="webSearch('site:kuchnialidla.pl')">Kuchnia Lidla</button></div></div><div class="panel"><h3>Import</h3><p class="muted">Po znalezieniu przepisu możesz skopiować jego treść i użyć „Dodaj z tekstu”. Zachowujemy Twoją wersję lokalnie.</p><button class="primary" onclick="openImportText()">↥ Dodaj przepis z tekstu</button></div>`}
function more(){return `<div class="hero"><div class="eyebrow">Kucharzyna</div><h1>Więcej</h1><p>Ustawienia, backup i zarządzanie bazą.</p></div><div class="panel"><h3>Wygląd</h3><div class="toggle"><span>Ciemny motyw</span><input type="checkbox" ${state.settings.dark===true?'checked':''} onchange="state.settings.dark=this.checked;save();render()"></div><button class="secondary" style="width:100%;margin-top:10px" onclick="state.settings.dark=null;save();render()">Zgodnie z iPhonem</button></div><div class="panel"><h3>Dane</h3><button class="secondary" style="width:100%;margin-bottom:8px" onclick="exportData()">↓ Eksportuj backup</button><button class="secondary" style="width:100%;margin-bottom:8px" onclick="document.getElementById('importFile').click()">↑ Importuj backup</button><input id="importFile" type="file" accept="application/json" style="display:none" onchange="importData(this)"><button class="secondary danger" style="width:100%" onclick="resetData()">Resetuj Kucharzynę</button></div><div class="panel"><h3>Ważne</h3><p class="muted">Receptury, notatki i lista zakupów są przechowywane lokalnie w przeglądarce. Eksportuj backup regularnie, jeśli zależy Ci na danych.</p></div>`}
function openRecipe(id){selected=state.recipes.find(r=>r.id===id);render()}
function toggleFav(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render()}
function modal(html){document.getElementById('modalRoot').innerHTML=`<div class="modal-back" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function ingredientInputs(rows){return rows.map(x=>`<div class="ingredient-edit"><input class="mini ing-name" placeholder="Składnik" value="${esc(x[0])}"><input class="mini ing-amt" type="number" step="any" placeholder="ilość" value="${x[1]??''}"><input class="mini ing-unit" placeholder="g/ml/szt" value="${esc(x[2])}"><button type="button" class="remove" onclick="this.parentElement.remove()">×</button></div>`).join('')}
function openAdd(){modal(`<div class="modal-head"><h2>Nowa receptura</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="saveNew(event)"><label class="label">Nazwa</label><input id="fName" required placeholder="np. Sos pomidorowy"><label class="label">Kategoria</label><input id="fCat" required placeholder="np. Sosy"><label class="label">Wydajność</label><input id="fYield" placeholder="np. 20 porcji"><label class="label">Źródło / URL (opcjonalnie)</label><input id="fSource" type="url" placeholder="https://..."><label class="label">Składniki</label><div id="ings">${ingredientInputs([['','','']])}</div><button type="button" class="secondary" onclick="addIngredientInput()">＋ Dodaj składnik</button><label class="label">Technologia</label><textarea id="fSteps" class="textarea" placeholder="Każdy etap w osobnej linii"></textarea><label class="label">Własne uwagi</label><textarea id="fNotes" class="textarea" placeholder="Twoje uwagi, poprawki, obserwacje..."></textarea><button class="primary">Zapisz recepturę</button></form>`)}
function addIngredientInput(){document.getElementById('ings').insertAdjacentHTML('beforeend',ingredientInputs([['','','']]))}
function collectIngredients(){return [...document.querySelectorAll('#ings .ingredient-edit')].map(r=>[r.querySelector('.ing-name').value.trim(),parseFloat(r.querySelector('.ing-amt').value)||0,r.querySelector('.ing-unit').value.trim()]).filter(x=>x[0])}
function saveNew(e){e.preventDefault();const r={id:'r-'+Date.now(),name:fName.value.trim(),category:fCat.value.trim(),yield:fYield.value.trim(),ingredients:collectIngredients(),steps:fSteps.value.split('\n').map(x=>x.trim()).filter(Boolean),notes:fNotes.value.trim(),source:fSource.value.trim(),tags:[]};state.recipes.unshift(r);save();closeModal();selected=r;render();toast('Receptura zapisana')}
function openEdit(id){const r=state.recipes.find(x=>x.id===id);modal(`<div class="modal-head"><h2>Edytuj recepturę</h2><button class="close" onclick="closeModal()">×</button></div><form class="form" onsubmit="saveEdit(event,'${r.id}')"><label class="label">Nazwa</label><input id="eName" value="${esc(r.name)}" required><label class="label">Kategoria</label><input id="eCat" value="${esc(r.category)}" required><label class="label">Wydajność</label><input id="eYield" value="${esc(r.yield||'')}"><label class="label">Źródło / URL</label><input id="eSource" type="url" value="${esc(r.source||'')}"><label class="label">Składniki</label><div id="ings">${ingredientInputs(r.ingredients)}</div><button type="button" class="secondary" onclick="addIngredientInput()">＋ Dodaj składnik</button><label class="label">Technologia</label><textarea id="eSteps" class="textarea">${esc(r.steps.join('\n'))}</textarea><label class="label">Własne uwagi</label><textarea id="eNotes" class="textarea">${esc(r.notes||'')}</textarea><button class="primary">Zapisz zmiany</button></form>`)}
function saveEdit(e,id){e.preventDefault();const r=state.recipes.find(x=>x.id===id);Object.assign(r,{name:eName.value.trim(),category:eCat.value.trim(),yield:eYield.value.trim(),source:eSource.value.trim(),ingredients:collectIngredients(),steps:eSteps.value.split('\n').map(x=>x.trim()).filter(Boolean),notes:eNotes.value.trim()});save();closeModal();selected=r;render();toast('Zmiany zapisane')}
function openScale(id){const r=state.recipes.find(x=>x.id===id);modal(`<div class="modal-head"><h2>Przelicz recepturę</h2><button class="close" onclick="closeModal()">×</button></div><label class="label">Mnożnik</label><input id="mult" type="number" step="0.1" value="1" oninput="renderScale('${r.id}')"><div id="scaled" class="panel">${scaledRows(r,1)}</div>`)}
function scaledRows(r,m){return r.ingredients.map(i=>`<div class="ingredient"><div>${esc(i[0])}</div><div class="amount">${Math.round(i[1]*m*100)/100}</div><div class="unit">${esc(i[2])}</div></div>`).join('')}
function renderScale(id){const r=state.recipes.find(x=>x.id===id);document.getElementById('scaled').innerHTML=scaledRows(r,parseFloat(document.getElementById('mult').value)||1)}
function openImportText(){modal(`<div class="modal-head"><h2>Dodaj z tekstu</h2><button class="close" onclick="closeModal()">×</button></div><p class="muted">Wklej tekst przepisu. Kucharzyna spróbuje rozdzielić składniki i kroki. Potem wszystko możesz poprawić ręcznie.</p><form class="form" onsubmit="importText(event)"><label class="label">Tekst przepisu</label><textarea id="rawRecipe" class="textarea" style="min-height:240px" required placeholder="Nazwa...\nSkładniki:\n500 g mąki\n300 g wody\n...\nPrzygotowanie:\n1. ..."></textarea><button class="primary">Utwórz recepturę</button></form>`)}
function importText(e){e.preventDefault();const raw=rawRecipe.value.trim(),lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let name=lines[0]||'Nowa receptura',idx=lines.findIndex(x=>/składniki|ingredients/i.test(x));let prep=lines.findIndex(x=>/przygot|steps|instruk/i.test(x));let ingLines=lines.slice(idx>=0?idx+1:1,prep>=0?prep:Math.min(lines.length,10));let steps=lines.slice(prep>=0?prep+1:Math.min(lines.length,10));let ingredients=ingLines.map(x=>{let m=x.match(/^[-•*]?\s*(\d+(?:[.,]\d+)?)\s*([a-zA-ZąćęłńóśźżĄĆĘŁŃÓŚŹŻ]+)?\s+(.+)$/);return m?[m[3].replace(/^[-•*]\s*/,''),parseFloat(m[1].replace(',','.')),m[2]||'szt']:[x.replace(/^[-•*]\s*/,''),0,'']}).filter(x=>x[0]);let r={id:'r-'+Date.now(),name,category:'Import',yield:'',ingredients,steps:steps.map(x=>x.replace(/^\d+[.)]\s*/,'')),notes:'Zaimportowano z tekstu — sprawdź i popraw recepturę.',source:'',tags:[]};state.recipes.unshift(r);save();closeModal();selected=r;render();toast('Przepis zaimportowany')}
function webSearch(site=''){const q=(document.getElementById('webq')?.value||'przepis').trim();const url='https://www.google.com/search?q='+encodeURIComponent((site?site+' ':'')+q+' przepis');window.open(url,'_blank','noopener')}
function addIngredientsToShopping(id){const r=state.recipes.find(x=>x.id===id);r.ingredients.forEach(i=>state.shopping.push({name:i[0],amount:i[1],unit:i[2],done:false}));save();toast('Dodano składniki do zakupów')}
function toggleShop(i){state.shopping[i].done=!state.shopping[i].done;save();render()}
function clearDone(){state.shopping=state.shopping.filter(x=>!x.done);save();render()}
function deleteRecipe(id){if(!confirm('Usunąć tę recepturę?'))return;state.recipes=state.recipes.filter(x=>x.id!==id);state.favorites=state.favorites.filter(x=>x!==id);selected=null;save();render();toast('Usunięto')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kucharzyna-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(inp){const f=inp.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!x.recipes)throw 0;state={...state,...x};save();render();toast('Backup zaimportowany')}catch(e){alert('Nieprawidłowy backup')}};rd.readAsText(f)}
function resetData(){if(confirm('Na pewno usunąć dane?')){state={recipes:seed,shopping:[],favorites:[],sources:[],settings:{dark:null}};save();selected=null;render();toast('Zresetowano')}}
document.getElementById('tabbar').addEventListener('click',e=>{const b=e.target.closest('button[data-tab]');if(!b)return;selected=null;currentTab=b.dataset.tab;render()});document.getElementById('quickAdd').onclick=openAdd;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
